#!/bin/bash
# GitHub 推送脚本
# 需要 Personal Access Token

echo "=== GitHub 推送助手 ==="
echo ""
echo "⚠️ 重要：GitHub 不能用密码推送，需要 Personal Access Token"
echo ""
echo "📝 请按以下步骤操作："
echo ""
echo "1️⃣ 在浏览器打开：https://github.com/settings/tokens"
echo ""
echo "2️⃣ 点击 'Generate new token (classic)'"
echo ""
echo "3️⃣ 填写："
echo "   - Note: llm-awesome-push"
echo "   - Expiration: No expiration"
echo "   - Scopes: 勾选 ✅ repo (全选)"
echo ""
echo "4️⃣ 点击 'Generate token'，复制生成的 token"
echo ""
echo "5️⃣ 回到这里，运行："
echo "   export GITHUB_TOKEN=你的 token"
echo "   ./push_to_github.sh"
echo ""
echo "=== 或者手动推送 ==="
echo ""
echo "1. 访问 https://github.com/new"
echo "2. 仓库名：awesome-llm-resources"
echo "3. 选择 Public"
echo "4. 不要勾选 README/.gitignore/license"
echo "5. 点击 Create repository"
echo "6. 复制页面命令运行："
echo ""
echo "   cd /Users/lxd/.openclaw/workspace/llm-awesome"
echo "   git remote add origin https://github.com/你的用户名/awesome-llm-resources.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
